// 该文件定义“发布/编辑”界面的四个模块主题：出售、收购、帮帮忙、失物招领
// 每个主题包含：标题、图标、色板（头部背景、强调色、输入聚焦、按钮颜色等）、
// 以及在表单中的占位/帮助文案，方便在 PostModal 中按类型切换。

export const MODULE_THEMES = {
  sale: {
    key: 'sale',
    title: '发布 · 出售商品',
    icon: '🛒',
    headerBg: 'bg-gradient-to-r from-indigo-600 to-indigo-500',
    headerText: 'text-white',
    accentPill: 'bg-indigo-50 text-indigo-700',
    accentBorder: 'border-indigo-200',
    inputFocus: 'focus:ring-indigo-500 focus:border-indigo-500',
  buttonBg: 'bg-indigo-600 hover:bg-indigo-700',
    buttonText: 'text-white',
  priceText: 'text-indigo-600',
  outlineHoverText: 'hover:text-indigo-600',
  outlineHoverBorder: 'hover:border-indigo-300',
  softBg: 'bg-indigo-50',
    priceLabel: '价格* (元)',
    titlePlaceholder: '例：九成新 iPad 2021 款 64G',
    descPlaceholder: '补充成色、购买时间、配件、交易地点等信息',
    descHelp: '请尽量提供清晰完整的信息，便于买家决策。',
    imageHelp: '支持 JPG/PNG，最多 10 张，推荐上传清晰实拍图。',
    categoryLabel: '商品分类',
  },
  acquire: {
    key: 'acquire',
    title: '发布 · 收购需求',
    icon: '📦',
    headerBg: 'bg-gradient-to-r from-emerald-600 to-emerald-500',
    headerText: 'text-white',
    accentPill: 'bg-emerald-50 text-emerald-700',
    accentBorder: 'border-emerald-200',
    inputFocus: 'focus:ring-emerald-500 focus:border-emerald-500',
  buttonBg: 'bg-emerald-600 hover:bg-emerald-700',
    buttonText: 'text-white',
  priceText: 'text-emerald-600',
  outlineHoverText: 'hover:text-emerald-600',
  outlineHoverBorder: 'hover:border-emerald-300',
  softBg: 'bg-emerald-50',
    priceLabel: '预算* (元)',
    titlePlaceholder: '例：求购二手显示器 24 寸 IPS',
    descPlaceholder: '描述关键需求，如品牌/型号/功能/期望成色/交付时间等',
    descHelp: '描述越清晰，越容易匹配到合适的卖家。',
    imageHelp: '可上传参考图（选填）。',
    categoryLabel: '需求分类',
  },
  help: {
    key: 'help',
    title: '发布 · 帮帮忙',
    icon: '🆘',
    headerBg: 'bg-gradient-to-r from-orange-500 to-orange-400',
    headerText: 'text-white',
    accentPill: 'bg-orange-50 text-orange-700',
    accentBorder: 'border-orange-200',
    inputFocus: 'focus:ring-orange-500 focus:border-orange-500',
  buttonBg: 'bg-orange-500 hover:bg-orange-600',
    buttonText: 'text-white',
  outlineHoverText: 'hover:text-orange-600',
  outlineHoverBorder: 'hover:border-orange-300',
  softBg: 'bg-orange-50',
    priceLabel: null, // 不显示价格
    titlePlaceholder: '例：求助安装开发环境（Windows）',
    descPlaceholder: '说明求助背景、已尝试方案、希望得到的帮助以及时间要求',
    descHelp: '请保持礼貌与耐心，提供必要信息以便他人帮助你。',
    imageHelp: '可上传说明性截图（选填）。',
    categoryLabel: '求助类型',
  },
  lostfound: {
    key: 'lostfound',
    title: '发布 · 失物招领',
    icon: '📢',
    headerBg: 'bg-gradient-to-r from-sky-600 to-sky-500',
    headerText: 'text-white',
    accentPill: 'bg-sky-50 text-sky-700',
    accentBorder: 'border-sky-200',
    inputFocus: 'focus:ring-sky-500 focus:border-sky-500',
  buttonBg: 'bg-sky-600 hover:bg-sky-700',
    buttonText: 'text-white',
  outlineHoverText: 'hover:text-sky-600',
  outlineHoverBorder: 'hover:border-sky-300',
  softBg: 'bg-sky-50',
    priceLabel: null, // 不显示价格
    titlePlaceholder: '例：图书馆遗失黑色背包（内有学生证）',
    descPlaceholder: '描述丢失/捡到的时间、地点、特征及联系方式等',
    descHelp: '请保护隐私并注意线下见面安全。',
    imageHelp: '建议上传物品照片或地点示意图（选填）。',
    categoryLabel: '信息类型',
  },
};

export const getModuleTheme = (type) => MODULE_THEMES[type] || MODULE_THEMES.sale;
